default: &default
  adapter: postgresql
  username: root
  password:
  timeout: 5000

development:
  <<: *default
  adapter: sqlite
  database: apna_menu

test:
  <<: *default
  database: apna_menu

production:
  <<: *default
  database: apna_menu
